-app
    - node_modules
    - routes
        - __init.py
        - auth_routes.py
        - cliente_routes.py
        - dashboard_routes.py
        - produtos_routes.py
        - export_routes.py
        - models.py
    - static
        - css
            - clientes.js
            - dashboard.css
            - login.css
            - pendencias.css
        - img
        - js
            - clientes.js
            - login.js
            - pendencias.js
    - templates
        - clientes.html
        - dashboard.html
        - index.html
        - login.html
        - pendencias.html
    - tests
    - __init.py
    - .env
    - config.py
    - helpers.py
    - packpage.-lock.json
    - README.md
    - requirements.txt
run.py